### PR TITLE
update readme with progress example

### LINKED ISSUE #95: No example using the progress callback argument.
Digging through the code base I found the progress call back you can pass to the scpclient class. I found that pretty helpful and it would be a good thing to document in the readme.

### PR DESCRIPTION
**Pull request by nanomosfet**
Closes #95

### CODE REVIEW

**Comment by remram44** [comment]
Thanks for this! I think this is a nice addition. Do you think you can update the previous comments that read "*SCPClient takes a paramiko transport as its only argument*", since that is no longer the case?

**Comment by nanomosfet** [comment]
How about we say "SCPClient only needs a paramiko transport to initialize."

**Comment by remram44** [comment]
I think removing "only" is probably enough. People can refer to the documentation to get an exhaustive list of arguments...

Python 2.6 fails because Paramiko no longer supports it, there's not much we can do apart from removing it from our own Travis config 🙁

**Comment by nanomosfet** [comment]
After work ill go ahead and make another commit.

**Comment by nanomosfet** [comment]
Okay commited.

Let me know if there is anything else!

**Comment by remram44** [comment]
Works for me!

**Pull request merged**
