### PR TITLE
doc: add install package steps

### PR DESCRIPTION
**Pull request by Antonio-Costa00**

### CODE REVIEW

**Comment by remram44** [comment]
Not required, `scp` depends on `paramiko`.

This package can be installed in the usual ways, with `pip install scp` or `poetry add scp` or `conda install scp` or `python3 setup.py install`, I am not sure if installation steps are required?

**Comment by Antonio-Costa00** [comment]
I think it's important in case someone wants to use just the `scp`, without the functionalities of the `paramiko`  package.

**Comment by remram44** [comment]
I don't understand. Whether or not you use paramiko directly, you need paramiko for scp to work (or to install it at all).

**Comment by Antonio-Costa00** [comment]
Yep. That's why I think it's important to have a describe of how to install the packages top use `scp`package.

**Pull request closed without merging**
