### PR TITLE
Remove extra space in SSH command sent on get()

### LINKED ISSUE #158: Freebsd (Juniper Junos) not happy with extra space in Secure Copy get
I started running into this over the weekend and I tracked it down to changes in 0.13.4 (versus 0.13.3).

Junos (uses freebsd) is not happy when there is an extra space after `scp`

So it works fine when the `exec_command` is: `b'scp -f /var/tmp/test9.txt'`

But it fails when it is `b'scp  -f /var/tmp/test9.txt'` (two spaces between the scp and the -f)

See:

https://github.com/ktbyers/netmiko/issues/2339

I will probably see if I can do a PR on this.

### PR DESCRIPTION
**Pull request by remram44**
Fixes #158

### CODE REVIEW

**Comment by remram44** [comment]
@ktbyers let me know if that fixes your issue, and I'll make a new release. Thanks!

**Comment by ktbyers** [comment]
Testing now.

**Comment by ktbyers** [comment]
Yep, all my Secure Copy tests look good now:

```
$PYTEST test_netmiko_scp.py --test_device cisco3 \
> && $PYTEST test_netmiko_scp.py --test_device arista_sw \
> && $PYTEST test_netmiko_scp.py --test_device juniper_srx \
> && $PYTEST test_netmiko_scp.py --test_device cisco_xrv \
> && $PYTEST test_netmiko_scp.py --test_device nxos1 \
> && $PYTEST test_netmiko_scp.py --test_device linux_srv1
============================================ test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 12 items                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods PASSED
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get PASSED
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

============================================ 12 passed in 23.35s ============================================
============================================ test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 12 items                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods PASSED
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get PASSED
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

============================================ 12 passed in 47.64s ============================================
============================================ test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 12 items                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods PASSED
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get PASSED
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

============================================ 12 passed in 39.55s ============================================
============================================ test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 12 items                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods PASSED
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get PASSED
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

============================================ 12 passed in 48.80s ============================================
============================================ test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 12 items                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods PASSED
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get PASSED
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

============================================ 12 passed in 44.33s ============================================
============================================ test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 12 items                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods PASSED
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get PASSED
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

============================================ 12 passed in 37.31s ============================================
```

**Comment by ktbyers** [comment]
So all good from my perspective.

**Comment by ktbyers** [comment]
@remram44 Thanks for doing the fix so quickly and doing a new release...much appreciated :-)

**Pull request merged**
